version: '3.6'

services:
  app:
    container_name: todo
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./app:/home
    ports:
      - 8000:8000